# Generated by Django 4.1.2 on 2022-11-28 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=500)),
                ('gender', models.TextField(choices=[('male', 'Male'), ('female', 'Female')])),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
    ]
