# Generated by Django 4.1.2 on 2022-11-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achu', '0002_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feesdate', models.CharField(max_length=50)),
            ],
        ),
    ]
