# Generated by Django 4.1.2 on 2022-12-05 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achu', '0004_product_delete_course_delete_fees_delete_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(max_length=500),
        ),
    ]
